[package]
name = "relay-sr201"
version = "0.1.0"
authors = ["Kyle Manna <kyle@kylemanna.com>"]
edition = "2018"
description = "SR-201 Network Relay Controller"
license = "MIT"

[dependencies]
regex = "1"
structopt = { version = "0.3" }
